// autogenerated by cmake

#ifndef _DLIBS_H_
#define _DLIBS_H_

#define DLIBS_MAJOR @Dlibs_MAJOR_VERSION@
#define DLIBS_MINOR @Dlibs_MINOR_VERSION@
#define DLIBS_PATCH @Dlibs_PATCH_LEVEL@
#define DLIBS_VERSION "@Dlibs_VERSION@"

#define DLIBS_PREFIX_PATH "@CMAKE_INSTALL_PREFIX@"
#define DLIBS_PACKAGE_NAME "@PROJECT_NAME@"
#define DLIBS_BUG_REPORT "@Dlibs_BUGREPORT@"

#endif // _DLIBS_H_