/******************************************************************************
 *      ____              ____    _       _   _                               *
 *     /# /_\_           |  _ \  (_)   __| | (_)   ___   _ __                 *
 *    |  |/o\o\          | | | | | |  / _` | | |  / _ \ | '__|                *
 *    |  \\_/_/          | |_| | | | | (_| | | | |  __/ | |                   *
 *   / |_   |            |____/  |_|  \__,_| |_|  \___| |_|                   *
 *  |  ||\_ ~|                                                                *
 *  |  ||| \/                                                                 *
 *  |  |||       Project : DLibs : usefull tools for C++ programming          *
 *  \//  |                                                                    *
 *   ||  |       Developper : Didier FABERT <didier.fabert@gmail.com>         *
 *   ||_  \      Date : 2009, April                                           *
 *   \_|  o|                                             ,__,                 *
 *    \___/      Copyright (C) 2009 by didier fabert     (oo)____             *
 *     ||||__                                            (__)    )\           *
 *     (___)_)   File : config.h                            ||--|| *          *
 *                                                                            *
 *   This program is free software; you can redistribute it and/or modify     *
 *   it under the terms of the GNU General Public License as published by     *
 *   the Free Software Foundation; either version 3 of the License, or        *
 *   (at your option) any later version.                                      *
 *                                                                            *
 *   This program is distributed in the hope that it will be useful,          *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of           *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            *
 *   GNU General Public License for more details.                             *
 *                                                                            *
 *   You should have received a copy of the GNU General Public License        *
 *   along with this program; if not, write to the                            *
 *   Free Software Foundation, Inc.,                                          *
 *   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.             *
 ******************************************************************************/
// autogenerated by cmake

#ifndef _CONFIG_H_
#define _CONFIG_H_

#define DLIBS_MAJOR @Dlibs_MAJOR_VERSION@
#define DLIBS_MINOR @Dlibs_MINOR_VERSION@
#define DLIBS_PATCH @Dlibs_PATCH_LEVEL@
#define DLIBS_SOVERSION @Dlibs_SOVERSION@
#define DLIBS_VERSION "@Dlibs_VERSION@"
#cmakedefine WITH_EXCEPTIONS
#cmakedefine DLIBS_HAVE_MYSQL
#cmakedefine DLIBS_HAVE_PGSQL

#define DLIBS_PREFIX_PATH "@CMAKE_INSTALL_PREFIX@"
#define DLIBS_PACKAGE_NAME "@PROJECT_NAME@"
#define DLIBS_BUG_REPORT "@Dlibs_BUGREPORT@"

#endif // _CONFIG_H_
